"""add item description

Revision ID: 3e2da3791ecc
Revises: d2b2c62b0590
Create Date: 2026-04-07 11:21:01.069802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2da3791ecc'
down_revision: Union[str, Sequence[str], None] = 'd2b2c62b0590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_item', sa.Column('description', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_item', 'description')
    # ### end Alembic commands ###
